Buildall: Revert rootfs reuse completely, improvements

diff --git a/bin/buildall.in b/bin/buildall.in
--- a/bin/buildall.in
+++ b/bin/buildall.in
@@ -11,12 +11,7 @@ function goto
 # $1 last $2 next
 function advancedir
 {
-    if [ -e /var/cache/garuda-tools/garuda-chroots/buildiso/$1/x86_64/build.make_image_root ]; then
-        mkdir -p /var/cache/garuda-tools/garuda-chroots/buildiso/$2/x86_64/ /var/cache/garuda-tools/garuda-chroots/buildiso/$2/iso/garuda/x86_64/
-        mv /var/cache/garuda-tools/garuda-chroots/buildiso/$1/x86_64/{rootfs,build.make_image_root} /var/cache/garuda-tools/garuda-chroots/buildiso/$2/x86_64/
-        mv /var/cache/garuda-tools/garuda-chroots/buildiso/$1/iso/garuda/x86_64/rootfs* /var/cache/garuda-tools/garuda-chroots/buildiso/$2/iso/garuda/x86_64/
-        rm -rf /var/cache/garuda-tools/garuda-chroots/buildiso/$1
-    fi
+    rm -rf --one-file-system /var/cache/garuda-tools/garuda-chroots/buildiso/*
 }
 
 rm -rf /var/cache/garuda-tools/garuda-chroots/buildiso/*
@@ -24,163 +19,111 @@ buildiso -i
 
 source /var/cache/garuda-tools/garuda-builds/.env
 
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/bspwm/$(date +%y%m%d)/*.iso; then
-    goto dr460nized
-else 
-    if buildiso -p bspwm; then
-        goto dr460nized
-    else echo "BSPWM ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/bspwm/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p bspwm; then
+        echo "BSPWM ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "BSPWM" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: dr460nized
-advancedir bspwm dr460nized
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized/$(date +%y%m%d)/*.iso; then
-    goto dr460nized-blackarch
-else 
-    if buildiso -p dr460nized; then
-        goto dr460nized-blackarch
-    else echo "Dr460nized ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p dr460nized; then
+        echo "Dr460nized ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Dr460nized" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: dr460nized-blackarch
-advancedir dr460nized dr460nized-blackarch
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-blackarch/$(date +%y%m%d)/*.iso; then
-    goto dr460nized-gaming
-else 
-    if buildiso -p dr460nized-blackarch; then
-        goto dr460nized-gaming
-    else echo "Dr460nized-blackarch ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-blackarch/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p dr460nized-blackarch; then
+        echo "Dr460nized-blackarch ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Dr460nized-blackarch" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: dr460nized-gaming
-advancedir dr460nized-blackarch dr460nized-gaming
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-gaming/$(date +%y%m%d)/*.iso; then
-    goto gnome
-else 
-    if buildiso -p dr460nized-gaming -f; then
-        goto gnome
-    else echo "Dr460nized Gaming ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-gaming/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p dr460nized-gaming -f; then
+        echo "Dr460nized Gaming ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Dr460nized Gaming" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: gnome
-advancedir dr460nized-gaming gnome
+cleardir
 if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/gnome/$(date +%y%m%d)/*.iso; then
-    goto gnome-barebones
-else 
-    if buildiso -p gnome; then
-        goto gnome-barebones
-    else echo "GNOME ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+    if ! buildiso -p gnome; then
+        echo "GNOME ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "GNOME" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: gnome-barebones
-advancedir gnome gnome-barebones
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/gnome-barebones/$(date +%y%m%d)/*.iso; then
-    goto i3
-else 
-    if buildiso -p gnome-barebones -k linux-lts; then
-        goto i3
-    else echo "GNOME Barebones ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/gnome-barebones/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p gnome-barebones -k linux-lts; then
+        echo "GNOME Barebones ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "GNOME Barebones" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: i3
-advancedir gnome-barebones i3
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/i3/$(date +%y%m%d)/*.iso; then
-    goto kde-barebones
-else 
-    if buildiso -p i3; then
-        goto kde-barebones
-    else echo "i3 ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/i3/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p i3; then
+        echo "i3 ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "i3" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: kde-barebones
-advancedir i3 kde-barebones
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/kde-barebones/$(date +%y%m%d)/*.iso; then
-    goto lxqt-kwin
-else 
-    if buildiso -p kde-barebones -k linux-lts; then
-        goto lxqt-kwin
-    else echo "KDE Barebones ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/kde-barebones/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p kde-barebones -k linux-lts; then
+        echo "KDE Barebones ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "KDE Barebones" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: lxqt-kwin
-advancedir kde-barebones lxqt-kwin
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/lxqt-kwin/$(date +%y%m%d)/*.iso; then
-    goto qtile
-else 
-    if buildiso -p lxqt-kwin; then
-        goto qtile
-    else echo "LXQT-Kwin ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/lxqt-kwin/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p lxqt-kwin; then
+        echo "LXQT-Kwin ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "LXQT-Kwin" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: qtile
-advancedir lxqt-kwin qtile
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/qtile/$(date +%y%m%d)/*.iso; then
-    goto sway
-else 
-    if buildiso -p qtile; then
-        goto sway
-    else echo "Qtile ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/qtile/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p qtile; then
+        echo "Qtile ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Qtile" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: sway
-advancedir qtile sway
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/sway/$(date +%y%m%d)/*.iso; then
-    goto wayfire
-else 
-    if buildiso -p sway; then
-        goto wayfire
-    else echo "Sway ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/sway/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p sway; then
+        echo "Sway ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Sway" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: wayfire
-advancedir sway wayfire
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/wayfire/$(date +%y%m%d)/*.iso; then
-    goto xfce
-else 
-    if buildiso -p wayfire; then
-        goto xfce
-    else echo "Wayfire ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/wayfire/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p wayfire; then
+        echo "Wayfire ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "Wayfire" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: xfce
-advancedir wayfire xfce
-if  test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/xfce/$(date +%y%m%d)/*.iso; then
-    goto ready
-else 
-    if buildiso -p xfce -k linux-lts; then
-        goto ready
-    else echo "XFCE ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+cleardir
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/xfce/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p xfce -k linux-lts; then
+        echo "XFCE ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
         echo "XFCE" >> /var/cache/garuda-tools/rebuild_needed.log
     fi
 fi
 
-: ready
-[ -e /var/cache/garuda-tools/rebuild_needed.log ] && cat /var/cache/garuda-tools/rebuild_needed.log | apprise -vv "${TELEGRAM}" -t "Failed builds"
-rm /var/cache/garuda-tools/rebuild_needed.log
-rm -rf /var/cache/garuda-tools/garuda-chroots/buildiso/*
+cat /var/cache/garuda-tools/rebuild_needed.log | apprise -vv "${TELEGRAM}" -t "Failed builds"
+rm -rf /var/cache/garuda-tools/rebuild_needed.log
+cleardir
 exit
 
