restructure buildall

diff --git a/bin/buildall.in b/bin/buildall.in
--- a/bin/buildall.in
+++ b/bin/buildall.in
@@ -15,122 +15,11 @@ function cleardir
 }
 
 cleardir
+
 buildiso -i
 
 source /var/cache/garuda-tools/garuda-builds/.env
 
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/bspwm/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p bspwm; then
-        echo "BSPWM ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "BSPWM" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p dr460nized; then
-        echo "Dr460nized ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Dr460nized" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-blackarch/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p dr460nized-blackarch; then
-        echo "Dr460nized-blackarch ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Dr460nized-blackarch" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-gaming/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p dr460nized-gaming -f; then
-        echo "Dr460nized Gaming ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Dr460nized Gaming" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/gnome/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p gnome; then
-        echo "GNOME ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "GNOME" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/i3/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p i3; then
-        echo "i3 ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "i3" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/kde-barebones/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p kde-barebones -k linux-lts; then
-        echo "KDE Barebones ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "KDE Barebones" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/kde-git/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p kde-git; then
-        echo "KDE-git ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "KDE-git" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/lxqt-kwin/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p lxqt-kwin; then
-        echo "LXQT-Kwin ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "LXQT-Kwin" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/cinnamon/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p cinnamon; then
-        echo "Cinnamon ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Cinnamon" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/mate/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p mate; then
-        echo "MATE ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "MATE" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/qtile/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p qtile; then
-        echo "Qtile ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Qtile" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/sway/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p sway; then
-        echo "Sway ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Sway" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
-if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/wayfire/$(date +%y%m%d)/*.iso; then
-    if ! buildiso -p wayfire; then
-        echo "Wayfire ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
-        echo "Wayfire" >> /var/cache/garuda-tools/rebuild_needed.log
-    fi
-fi
-
-cleardir
 if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/xfce/$(date +%y%m%d)/*.iso; then
     if ! buildiso -p xfce -k linux-lts; then
         echo "XFCE ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
@@ -139,5 +28,123 @@ if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/xfce/$(date +%y%m%
 fi
 
 cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p dr460nized; then
+        echo "Dr460nized ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Dr460nized" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/dr460nized-gaming/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p dr460nized-gaming -f; then
+        echo "Dr460nized Gaming ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Dr460nized Gaming" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/gnome/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p gnome; then
+        echo "GNOME ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "GNOME" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/i3/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p i3; then
+        echo "i3 ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "i3" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/kde-lite/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p kde-lite; then
+        echo "KDE lite ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "KDE lite" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/kde-git/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p kde-git; then
+        echo "KDE-git ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "KDE-git" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/lxqt-kwin/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p lxqt-kwin; then
+        echo "LXQT-Kwin ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "LXQT-Kwin" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/cinnamon/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p cinnamon; then
+        echo "Cinnamon ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Cinnamon" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/mate/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p mate; then
+        echo "MATE ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "MATE" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/garuda/sway/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p sway; then
+        echo "Sway ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Sway" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/wayfire/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p wayfire; then
+        echo "Wayfire ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Wayfire" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/bspwm/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p bspwm; then
+        echo "BSPWM ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "BSPWM" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
+if ! test -f /var/cache/garuda-tools/garuda-builds/iso/community/qtile/$(date +%y%m%d)/*.iso; then
+    if ! buildiso -p qtile; then
+        echo "Qtile ISO building failed. Manual intervention required!" | apprise -vv "${TELEGRAM}" -t "ISO Build failed!"
+        echo "Qtile" >> /var/cache/garuda-tools/rebuild_needed.log
+    fi
+fi
+
+cleardir
+
 exit
 
